# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 13) do

  create_table "annotation_assertions", :force => true do |t|
    t.column "context_id", :integer
    t.column "subject_reference_type", :string
    t.column "subject_reference_id", :integer, :default => 0
    t.column "subject_text", :text
    t.column "predicate_reference_type", :string
    t.column "predicate_reference_id", :integer, :default => 0
    t.column "predicate_text", :text
    t.column "object_reference_type", :string
    t.column "object_reference_id", :integer, :default => 0
    t.column "object_text", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "annotation_contexts", :force => true do |t|
    t.column "annotator_type", :string
    t.column "annotator_id", :integer
    t.column "name", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "cached_feeds", :force => true do |t|
    t.column "href", :string
    t.column "title", :string
    t.column "link", :string
    t.column "feed_data", :text
    t.column "feed_data_type", :string
    t.column "http_headers", :text
    t.column "last_retrieved", :datetime
  end

  create_table "comments", :force => true do |t|
    t.column "user_id", :integer
    t.column "title", :string
    t.column "comment", :string
    t.column "commentable_id", :integer
    t.column "commentable_type", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "state", :string, :default => "published"
  end

  create_table "entries", :force => true do |t|
    t.column "journal_id", :integer
    t.column "state", :string
    t.column "date", :date
    t.column "body", :text
    t.column "body_filtered", :text
    t.column "photo", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
  end

  create_table "groups", :force => true do |t|
    t.column "user_id", :integer
    t.column "title", :string
    t.column "description", :string
    t.column "state", :string
    t.column "scope", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
  end

  create_table "groups_journals", :id => false, :force => true do |t|
    t.column "group_id", :integer
    t.column "journal_id", :integer
  end

  create_table "groups_users", :id => false, :force => true do |t|
    t.column "group_id", :integer
    t.column "user_id", :integer
  end

  create_table "journals", :force => true do |t|
    t.column "user_id", :integer
    t.column "title", :string
    t.column "description", :text
    t.column "state", :string
    t.column "scope", :string
    t.column "start_date", :date
    t.column "end_date", :date
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "initial_count", :integer, :default => 1
    t.column "comment_state", :string, :default => "published"
  end

  create_table "model_statistics", :force => true do |t|
    t.column "instance_type", :string
    t.column "instance_id", :integer
    t.column "user_type", :string
    t.column "user_id", :integer
    t.column "request", :text
    t.column "referer", :text
    t.column "created_at", :datetime
    t.column "session_id", :string
    t.column "request_uri", :string
    t.column "remote_addr", :string
  end

  create_table "roles", :force => true do |t|
    t.column "title", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "user_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "settings", :force => true do |t|
    t.column "var", :string, :default => "", :null => false
    t.column "value", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "urlnames", :force => true do |t|
    t.column "nameable_type", :string
    t.column "nameable_id", :integer
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "email", :string
    t.column "state", :string
    t.column "scope", :string
    t.column "description", :text
    t.column "avatar", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "activation_code", :string, :limit => 40
    t.column "remember_token", :string, :limit => 40
    t.column "remember_token_expires_at", :datetime
    t.column "activated_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "time_zone", :string, :default => "UTC"
    t.column "annotation_context_id", :integer
    t.column "contact_permissions", :string, :default => "--- \n- news\n"
  end

end
